### ISSUE TITLE
Add a horizontal line to mark cyclethreshold on convergence plots

### ISSUE THREAD

**Issue by urvashirau** [casangi/casagui#16]
Add a horizontal line between each pair of major-cycle boundaries that marks the cyclethreshold for the minor cycle iterations performed in between.

The cyclethreshold information is contained within the tclean return dictionary, within the 'summaryminor' key for each image/chan/stokes plane. With CASA 6, this cycleThreshold is actually the same number for all channels/stokes/images because it is a single number calculated based on the peak residual across all channels.  But, a future (CASA6 and/or ngCASA) feature requirement is for iteration control to be completely independent per channel/stokes/image. This would make the cyclethreshold vary per plane, and this is why the current tclean return dictionary structure already includes this key in the per-plane dictionary structure.

**Comment by schiebel** [comment]
This is useful information. This is what the current implementation of this looks like:

![Image](https://user-images.githubusercontent.com/8408745/230494521-2f96e8ed-9e5e-4974-b0a4-22e3b7f694fd.png)

It uses the `cyclethreshold` value that is at the **top level** of the `tclean` dictionary:
```
{'cleanstate': 'running', 'cyclefactor': 3.0, 'cycleiterdone': 0, 'cycleniter': 10, 'cyclethreshold': 0.0396367684006691, 'interactiveiterdone': 10, 'interactivemode': False, 'interactiveniter': 0, 'interactivethreshold': 0.0, 'iterdone': 47, 'loopgain': 0.10000000149011612, 'maxpsffraction': 1.0, 'maxpsfsidelobe': 0.12576784193515778, 'minpsffraction': 0.0, 'niter': 492, 'nmajordone': 1, 'nsigma': 0.0, 'stopcode': 9, 'summarymajor': array([47]), 'summaryminor': {0: {0: {0: {'iterDone': [9.0], 'peakRes': [0.10003000497817993], 'modelFlux': [1.2997363805770874], 'cycleThresh': [0.10596474260091782]}}, 1: {0: {'iterDone': [9.0], 'peakRes': [0.10536947101354599], 'modelFlux': [1.9179407358169556], 'cycleThresh': [0.10596474260091782]}}, 2: {0: {'iterDone': [9.0], 'peakRes': [0.10193026065826416], 'modelFlux': [1.1851012706756592], 'cycleThresh': [0.10596474260091782]}}, 3: {0: {'iterDone': [10.0], 'peakRes': [0.09792544692754745], 'modelFlux': [0.7993731498718262], 'cycleThresh': [0.10596474260091782]}}, 4: {0: {'iterDone': [10.0], 'peakRes': [0.09717448800802231], 'modelFlux': [0.7046809196472168], 'cycleThresh': [0.10596474260091782]}}}}, 'threshold': 0.0010000000474974513, 'stopDescription': 'reached nmajor'}
```
i.e. here `0.0396367684006691`. Should it **instead** use `cycleThresh` here `[0.10596474260091782]` (with the values set per channel/per stokes plane)?

**Comment by urvashirau** [comment]
Yes, I believe so.  For reference (using a slightly older version of the return dict), look at cell 11 of [this notebook](file:///export/home/riya/rurvashi/Downloads/Example_Plots_Using_TClean_Return_Dictionary_jan22%20(1).html). 

The 'global' cyclethreshold returned is the value at the end of the run, whereas the one per channel is what was used for the minor cycle exit criterion.  The intent is for the dashed red line (without the points) to be flat from one major cycle boundary to the next.  If the 'stopreason' per minor-cycle set happens to be that it reached the cyclethreshold, then the peak residual value will match the dashed horizontal line, thus giving visual feedback of the stop reason.    ( In the plot above, you can see that the starting cyclethreshold value is indeed the peak residual value that that set of minor cycle iterations stopped at, but the dashed line moved down a bit too early. I hope that made sense. The reference plot from the linked notebook above may show it better.)

**Comment by schiebel** [comment]
Thanks @urvashirau, that was very helpful. This is the new convergence plot:


![Image](https://user-images.githubusercontent.com/8408745/231288107-4253a4da-59de-470e-8cba-99dc44ea615c.png)

Please let me know if this is what you had in mind.

**Comment by urvashirau** [comment]
Thank Darrell. Yes, this does contain the appropriate information.

Do you think it is a good idea to translate the 'stopcode' to the reason ? It would make it easier to read the plots. 

However, right now, this information is only in the documentation, and cannot be retrieved programmatically.  Would it make more sense to first require that this information be present in the tclean dictionary, and only then make a ticket here to add the info to the GUI ?

**Comment by schiebel** [comment]
Hi Urvashi, 

Yes I think converting this to a string would be a good idea. I think it would be good if there was a small library of imaging support functions (in Python) which would help with handling `tclean`'s return dictionary as well as the stop codes used in the imaging code.

On my end, it will be easy to make this change, but I'd rather not hard code the mappings within the vis software.
