### ISSUE TITLE
Interactive Clean history/plots don't persist across GUI instances

### ISSUE THREAD

**Issue by max-Hawkins** [casangi/casagui#23]
Calling Interactive Clean and running iterations aren't reflected after stopping the current instance and starting another. The convergence plot, image mask, and history should all reflect previous IC instances. (Unsure about all of these but am sure some of them should be at least). Thoughts @schiebel?

**Comment by max-Hawkins** [comment]
On the second IC iteration, Bokeh emits a warning: "BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('iterations', 2), ('stopCode', 2), ('threshold', 2), ('type', 1), ('values', 2)" Will have to look at this after finishing some other things up. Just wanted to open the issue for documentation.

**Comment by schiebel** [comment]
Hey @max-Hawkins I hope you had a good year!
