### ISSUE TITLE
tapedeck runtime error when imaging a single channel

### ISSUE THREAD

**Issue by jmarvil** [casangi/casagui#53]
I receive the following error when using specmode='mfs' or specmode='cube' plus nchan=1:

File casagui/toolbox/_cube.py:1417, in CubeMask.tapedeck(self) ...
RuntimeError: tapedeck can only be created after the slider has been created

I'm currently using CASA 6.6.4.19-py310, bokeh==3.2.2 and casagui==0.3.84

**Comment by schiebel** [comment]
Thanks for catching this. I believe it is resolved with v0.3.86.
